#!/bin/sh
# 当网络接口启动（ifup）时，该脚本会启用 QoSPlus 服务，并根据当前接口生成并应用 QoS 配置。

# 检查环境变量 ACTION 的值是否为 "ifup"
# ACTION 是一个由网络管理工具（如 ifupdown 或类似工具）设置的环境变量，
# 用于指示当前网络操作的状态，比如接口启动（ifup）或关闭（ifdown）。
[ "$ACTION" = ifup ] && 

# 如果 ACTION 等于 "ifup"，则执行以下操作：
# 1. 启用 QoSPlus 服务：
#    - 调用 /etc/init.d/qosplus 脚本的 enabled 方法，以启用 QoSPlus 服务。
#    - /etc/init.d/qosplus 是一个初始化脚本，通常用于管理 QoSPlus 服务的启动、停止和状态检查。
#    - enabled 方法通常是该脚本中的一个功能，用于启用或激活 QoSPlus 服务。
# 2. 生成并应用特定接口的 QoS 配置：
#    - 调用 /usr/lib/qosplus/generate.sh 脚本，传递两个参数：
#      - 第一个参数是 "interface"，表示操作的目标是网络接口。
#      - 第二个参数是 "$INTERFACE"，这是一个环境变量，表示当前正在启动的网络接口的名称（如 eth0、wlan0 等）。
#    - generate.sh 脚本会根据传入的接口名称生成相应的 QoS 配置命令。
#    - 生成的配置命令通过管道（|）传递给 sh（Shell 解释器）执行，以应用这些配置到当前启动的网络接口上。
#    - 这样做的目的是在网络接口启动时，自动配置该接口的 QoS 规则，以管理和优化网络流量。
/etc/init.d/qosplus enabled && /usr/lib/qosplus/generate.sh interface "$INTERFACE" | sh